(defproject scratch "0.1.0"
  :repositories
  [["clojars" {:url "https://clojars.org/repo/"}]
   ["maven-central" {:url "https://repo1.maven.org/maven2"}]
   ["project"  {:url  "file:resources" :username  "" :password  ""}]]
  :dependencies
  [[org.clojure/clojure "1.9.0-alpha17"]
   [aero "1.1.2"]
   [algebolic "1.0.0"]
   [aysylu/loom "1.0.0"]
   [better-cond "2.0.1-SNAPSHOT"]
   [bigml/sampling "3.0"]
   [clj-stacktrace "0.2.8"]
   [clj-time "0.14.0"]
   [com.cognitect/transit-clj "0.8.300"]
   [com.hypirion/clj-xchart "0.2.0"]
   [com.taoensso/timbre "4.10.0"]
   [complex "0.1.8"]
   [criterium "0.4.4"]
   [defun "0.3.0-RC1"]
   [expresso "0.2.2"]
   [gg4clj "0.1.0"]
   [huri "0.7.0-SNAPSHOT"]
   [io.aviso/pretty "0.1.34"]
   [kixi/stats "0.3.9"]
   [net.cgrand/xforms "0.9.2"]
   [net.mikera/clojure-utils "0.8.0"]
   [net.mikera/core.matrix "0.60.3"]
   [net.mikera/core.matrix.stats "0.7.0"]
   [net.mikera/vectorz-clj "0.47.0"]
   [org.clojure/algo.generic "0.1.2"]
   [org.clojure/core.async "0.3.443"]
   [org.clojure/core.logic "0.8.11"]
   [org.clojure/core.match "0.3.0-alpha5"]
   [org.clojure/data.csv "0.1.4"]
   [org.clojure/data.zip "0.1.2"]
   [org.clojure/math.combinatorics "0.1.4"]
   [org.clojure/math.numeric-tower "0.0.4"]
   [org.clojure/spec.alpha "0.1.123"]
   [org.clojure/tools.cli "0.3.5"]
   [org.clojure/tools.deps.alpha "0.1.29"]
   [org.clojure/tools.macro "0.1.2"]
   [org.clojure/tools.namespace "0.3.0-alpha4"]
   [org.clojure/tools.reader "1.0.5"]
   [org.clojure/tools.trace "0.7.9"]
   [org.flanagan/flanagan  "1.0.0"]
   [primitive-math "0.1.5"]
   [rhizome "0.2.7"]
   [rm-hull/infix "0.2.12"]
   [semantic-csv "0.2.1-alpha1"]
   [superstring "2.1.0"]
   [tesser.core "1.0.2"]
   [tesser.math "1.0.2"]
   [thinktopic/cortex "0.9.10"]
   [cquad "0.1.0"]

   [tide "0.2.0-SNAPSHOT" :exclusions [org.apache.commons/commons-math3]]]
  :source-paths ["src"]
  :resource-paths ["resources"]
  :repl-options {:init-ns user})

